// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDehSXkyV2YP99jUSm-_YXxgsp6MGIu9iU',
    appId: '1:1071489602786:web:da1f869e2adc5cc9ac3abb',
    messagingSenderId: '1071489602786',
    projectId: 'zero-waste-kitchen-90cee',
    authDomain: 'zero-waste-kitchen-90cee.firebaseapp.com',
    storageBucket: 'zero-waste-kitchen-90cee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTxAowJxikjJFyQe76n5R8sevDq-CCK1s',
    appId: '1:1071489602786:android:84fb2d788428ef7fac3abb',
    messagingSenderId: '1071489602786',
    projectId: 'zero-waste-kitchen-90cee',
    storageBucket: 'zero-waste-kitchen-90cee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrXTnj7FkappdLDrlMcXZbD_fudY6AgyA',
    appId: '1:1071489602786:ios:5ddbaad260859e6eac3abb',
    messagingSenderId: '1071489602786',
    projectId: 'zero-waste-kitchen-90cee',
    storageBucket: 'zero-waste-kitchen-90cee.appspot.com',
    iosClientId: '1071489602786-udom8p2cuo3n9chi6io2pq072jmr65pu.apps.googleusercontent.com',
    iosBundleId: 'np.com.shishirrijal.zero-waste-kitchen.RunnerTests',
  );
}
